export const types = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    GET_JWT: 'GET_JWT',
    SET_JWT: 'SET_JWT',
    GET_JWT_SUCCESS: 'GET_JWT_SUCCESS',
    GET_JWT_FAILED: 'GET_JWT_FAILED',
};
