export const types = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    GET_JWT: 'GET_JWT',
    SET_JWT: 'SET_JWT',
    GET_JWT_SUCCESS: 'GET_JWT_SUCCESS',
    GET_JWT_FAILED: 'GET_JWT_FAILED',

    GET_USER_DETAILS: 'GET_USER_DETAILS',
    GET_USER_DETAILS_SUCCESS: 'GET_USER_DETAILS_SUCCESS',
    GET_USER_DETAILS_FAIL: 'GET_USER_DETAILS_FAIL',

    GET_ROOM_MESSAGES: 'GET_ROOM_MESSAGES',
    GET_ROOM_MESSAGES_SUCCESS: 'GET_ROOM_MESSAGES_SUCCESS',
    GET_ROOM_MESSAGES_FAIL: 'GET_ROOM_MESSAGES_FAIL',

    GET_USER_MESSAGES: 'GET_USER_MESSAGES',
    GET_USER_MESSAGES_SUCCESS: 'GET_USER_MESSAGES_SUCCESS',
    GET_USER_MESSAGES_FAIL: 'GET_USER_MESSAGES_FAIL',

    SEND_MESSAGE: 'SEND_MESSAGE',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAIL: 'SEND_MESSAGE_FAIL',
};
